#!/bin/bash

echo " >> deploying cron job"
sleep 10

pip3 install git+https://github.com/philipn/django-rest-framework-filters

python3 convert_database_utf8.py
echo " >> starting app"
python3 manage.py makemigrations
python3 manage.py migrate
python3 manage.py loaddata deployment/dev/admin_fixture.json
python3 manage.py runserver 0.0.0.0:8000
