version: '3'

services:

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    ports:
    - "3305:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=backend
    networks: ['stack']

  api:
    image: api:latest
    build:
      context: deployment/dev/
      dockerfile: Dockerfile
    container_name: api
    volumes:
    - .:/app
    ports:
    - "4000:8000"
    depends_on:
    - mysqldb
    networks: ['stack']
    command: sh -c "sleep 10 && pip3 install mysql-connector-python && python3 convert_database_utf8.py && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

networks:
  stack:
    driver: bridge

