version: '3'

services:

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    ports:
    - "3305:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=backend
    networks: ['stack']

  api:
    image: api:latest
    build:
      context: deployment/dev/
      dockerfile: Dockerfile
    container_name: api
    volumes:
    - .:/app
    ports:
    - "4000:8000"
    depends_on:
    - mysqldb
    networks: ['stack']
    command: sh -c "sleep 20 && service cron restart &&pip3 install git+https://github.com/philipn/django-rest-framework-filters && python3 convert_database_utf8.py && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py loaddata deployment/dev/admin_fixture.json && python3 manage.py runserver 0.0.0.0:8000"


  react_front:
    image: react_front:latest
    build:
      context: front-end/
      dockerfile: Dockerfile
    container_name: react_front
    volumes:
    - ./front-end:/app
    ports:
      - "3000:3000"
    depends_on:
      - mysqldb
      - api
    networks: ['stack']
    command: npm start

networks:
  stack:
    driver: bridge

